# Generated by Django 5.2 on 2025-05-07 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_medicament', models.CharField(max_length=20, unique=True)),
                ('libelle_medicament', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Acte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_acte', models.CharField(max_length=20, unique=True)),
                ('libelle_acte', models.CharField(max_length=100)),
                ('montant_acte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_acte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrage.typeacte')),
            ],
        ),
    ]
