# Generated by Django 5.2 on 2025-05-07 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecins', '0001_initial'),
        ('parametrage', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_consultation', models.CharField(max_length=20, unique=True)),
                ('date_consultation', models.DateTimeField()),
                ('date_fin_validite_consultation', models.DateTimeField()),
                ('actes', models.ManyToManyField(blank=True, to='parametrage.acte')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecins.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ordonnance', models.CharField(max_length=20, unique=True)),
                ('date_ordonnance', models.DateTimeField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='OrdonnanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posologie_medicament', models.TextField()),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrage.medicament')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.ordonnance')),
            ],
        ),
    ]
