# Generated by Django 5.2 on 2025-05-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaires', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretaire',
            name='date_enregistrement',
        ),
        migrations.AddField(
            model_name='secretaire',
            name='titre_secretaire',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
