# Generated by Django 5.2 on 2025-05-07 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('parametrage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_facture', models.CharField(max_length=20, unique=True)),
                ('type_facture', models.CharField(max_length=100)),
                ('date_enreg_facture', models.DateTimeField()),
                ('date_paiement_facture', models.DateTimeField(blank=True, null=True)),
                ('montant_facture', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_paye_facture', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.consultation')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_validées', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FactureDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_facture_detail', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrage.acte')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentDate', models.DateTimeField()),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.facture')),
            ],
        ),
    ]
