# Generated by Django 5.2 on 2025-05-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='code_facture',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
