# Generated by Django 5.2 on 2025-05-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0002_medecin_utilisateur_alter_medecin_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
